### ISSUE TITLE
Failed to connect to robots: Service houseCleaning is not supported by your robot

### ISSUE THREAD

**Issue by bhuebschen** [trunneml/homeassistant-vorwerk#18]
Logger: custom_components.homeassistant-vorwerk
Source: custom_components/homeassistant-vorwerk/__init__.py:91
Integration: homeassistant-vorwerk

Failed to connect to robots: Service houseCleaning is not supported by your robot

**Comment by mjunold** [comment]
Same here with my VR300.
Seems to happen since the robot's update to Roboter Software Version 4.6.4-40.

Logger: custom_components.vorwerk
Source: custom_components/vorwerk/__init__.py:91
Integration: Vorwerk Kobold
First occurred: November 21, 2022 at 13:23:37 (5193 occurrences)
Last logged: 09:23:02
Failed to connect to robots: Unable to communicate with robot

**Comment by trunneml** [comment]
That are two different exceptions. 
My VR200 works, but it's just an VR200. 
when I'm getting such exceptions, normally the robot itself could not connect to the cloud. Could you please check:

- the robot status. Mine shows an red x in the display when there is a problem. 
- check if the robot works with the original App.

**Comment by mjunold** [comment]
Sorry, forgot to mention that: the original app is working fine. Status lights on robot are green.

**Comment by trunneml** [comment]
Okay, then they changed the API. Without a VR300 that will be a problem for me to implement.
We need to check if pybotvac has support for it. Then I can integrate it.

**Comment by bhuebschen** [comment]
problem disappeared all of a sudden 🤔

**Comment by bhuebschen** [comment]
> problem disappeared all of a sudden 🤔

and is back ... as suddenly as it was gone

**Comment by bhuebschen** [comment]
2022-12-22 15:33:20.071 WARNING (SyncWorker_40) [pybotvac.robot] Invalid response from https://nucleo.ksecosys.com/vendors/vorwerk/robots/############/messages: required key not provided @ data['availableServices']. Got: {'version': 1, 'reqId': '1', 'result': 'ko', 'data': {}}

**Comment by trunneml** [comment]
That error message is from the vorwerk cloud. Normally that happens when there is a connection problem between the robot and the cloud.
The VR200 shows in the display an red x when the connection to the cloud is broken. Could you check that? You can also try to reconnect your robot to wifi/cloud.
But as I mentioned before this error is on coming from the cloud and the cloud communication is done by this project, but by the underlying dependency `pybotvac`. Maybe the devs of `pybotvac` could help you.

**Comment by trunneml** [comment]
> 2022-12-22 15:33:20.071 WARNING (SyncWorker_40) [pybotvac.robot] Invalid response from https://nucleo.ksecosys.com/vendors/vorwerk/robots/############/messages: required key not provided @ data['availableServices']. Got: {'version': 1, 'reqId': '1', 'result': 'ko', 'data': {}}

Do you have any line number? Or could you provide the full stack trace?

But I have the feeling, that they changed the API. So may be you could also fill out a bug report here: https://github.com/stianaske/pybotvac/issues

**Comment by mjunold** [comment]
Sorry for having misled this topic, but maybe the solution from https://github.com/trunneml/homeassistant-vorwerk/issues/21 will help here, too?

**Comment by buzz-b** [comment]
Hi,

Thought I'd chime in with a me too, on the same error as [bhuebschen] on the 22nd Dec. 

2023-03-06 20:26:40.693 WARNING (SyncWorker_48) [pybotvac.robot] Invalid response from https://nucleo.ksecosys.com/vendors/vorwerk/robots/###########/messages: required key not provided @ data['availableServices']. Got: {'version': 1, 'reqId': '1', 'result': 'ko', 'error': 'ui_alert_invalid'}

I've a relatively up to date HASS Core version (2023.2.5) , and running Python 3.10 on Bullseye (under venv), however think it wasn't working a little before that, I've only just tried to get it going again after a while of previously working.

I've reloaded the integration 2 -3 times, no joy, and I removed the device from the App, and re-installed it there with a new name. redid the HASS integration and still get the same issue as above. So yes, sounds like the API has been changed, 

I have a VR200, and whilst it gets status updates ok, like battery life, I can't issue commands, I get the error above.

Please help, I'd love to get this going again. 
Thanks,
Andy...

**Comment by trunneml** [comment]
Sorry, I replaced my robot (VR200). So it is hard to help. The integration worked for me without a problem until September.
What I can tell you for the error is that the integration could talk to the vorwerk api, but that API returned an erro

**Comment by buzz-b** [comment]
Well I'm assuming from the actual error that the API now expects some JSON with the key "availableServices" in it, can you at least confirm if you're sending that or not, and maybe where I should look in the code to see where this is sent to nucleo so I can have a go at fixing it myself? I know a little bit of coding, but need pointing in the right direction. Please

**Comment by trunneml** [comment]
That is part of [pybotvac](https://github.com/stianaske/pybotvac). This repo is just a wrapper around it. It connects the login with a home-assistant config flow and presents the api results as sensors, etc...
All robot communiction related stuff is done in pybotvac.

**Comment by chatter80** [comment]
Hallo habe seit dem update auf die aktuelle Homeassistant Version 2025.1.0 das problem das nicht mehr alle Enitäten angezeigt werden.
Es werden nur noch die Schedule Enität angezeigt.

Kannst Du dir das bitte mal anschauen ? wäre toll würde auch gerne unterstützen damit die Integration weiter lauffähig ist ...

Danke

error LOG:

Logger: homeassistant.config_entries
Quelle: config_entries.py:855
Erstmals aufgetreten: 18:48:28 (3 Vorkommnisse)
Zuletzt protokolliert: 18:48:28

Error unloading entry xxx@xxx for vacuum
Error unloading entry xxx@xxx for switch
Error unloading entry xxx@xxx for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 216, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by trunneml** [comment]
Sorry, I do not longer own a Vorwerk. So I will archive this repo. Feel free to fork this repo.
